version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: app
    command: npm run start:dev
    restart: always
    build: .
    volumes: 
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo